env:
  browser: true
  es2021: true
  node: true
extends:
  - prettier
  - standard-with-typescript
  - plugin:prettier/recommended
plugins:
  - prettier
ignorePatterns:
  - dist
  - "src/wasm/base64.js"
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules:
  prettier/prettier: error
