env:
  browser: true
  es2022: true
  node: true
extends:
  - eslint:all
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - prettier
  - '@typescript-eslint'
ignorePatterns:
  - dist
overrides: []
rules:
  one-var: off
  no-magic-numbers: off
